### ISSUE TITLE
Add special HVV blob shapes and colours

### ISSUE THREAD

**Issue by echtnurich** [jheubuch/line-colors#1]
As per [this page](https://www.hvv.de/de/verkehrsangebot), HVV uses some special shapes which you might want to include.

Bus lines are generally displayed as an elongated hexagon, while ferries use a trapezoid.

**Comment by jheubuch** [comment]
So it would be nice to replace `rounded` with something like `shape`

**Comment by echtnurich** [comment]
On the topic of HVV specialties, there is also some colour shenanigans going on.

As you can see at [nimmbus.de Fahrplanbuch](https://www.nimmbus.de/fahrplanbuch/plaene/5813H-1.htm), some lines do not have solid block background, but rather an outline and characters in one colour, with a contrast filler.

**Comment by jheubuch** [comment]
> As you can see at [nimmbus.de Fahrplanbuch](https://www.nimmbus.de/fahrplanbuch/plaene/5813H-1.htm), some lines do not have solid block background, but rather an outline and characters in one colour, with a contrast filler.

I don't know if thats already a bit too specific and a bit overkill. Some edge cases are very difficult (looking at you, Munich's U7/U8), but I think for the first few thought I would define `shapes` without considering outlines/special colors in texts

> Also, HVV RE/RB lines do not seem to have any blob, how would one support transparent background?
Maybe by not stating any colour?

For that, I'd just would not add them to the list as they are "text only"

**Comment by echtnurich** [comment]
Yea, sounds like a plan.

shape: pill, hexagon, rectangle, trapezoid, ...

The inverted ones look to be confined to temporary services or on-demand services.

**Comment by jheubuch** [comment]
Shapes are now included
