### ISSUE TITLE
Different line color depending on the source: RE80 (and probably other lines too)

### ISSUE THREAD

**Issue by tomabrafix** [jheubuch/line-colors#7]
The RE80 has different line colors in official documents:

[AVV network plan](https://www.avv-augsburg.de/fileadmin/user_upload/Netzplaene_und_Karten/avv_schienennetzplan_2022_12_web.pdf): #006da7 (+ rounded)
[Bavaria network plan](https://www.mvv-muenchen.de/fileadmin/mediapool/03-Plaene_Bahnhoefe/Netzplaene/Bahnland-Bayern-Liniennetzplan.pdf): #008fbf
[GABY network plan](https://www.go-ahead.bayern/fileadmin/user_upload/GoAhead-Bayern/Bilder_Unterwegs/GABY_23_abn_Streckenband_A3_quer_230615.pdf): #096da9
[GABY timetable](https://www.go-ahead.bayern/fileadmin/user_upload/Fahrplan_Augsburg_Treuchtlingen_ab_11.06.2023.pdf): #006da7 (current color in line-colors.csv)
[VGN network plan](https://www.vgn.de/media/schienennetz-gesamtraum-vgn.pdf): #096da9

Which color should be used?

**Comment by jheubuch** [comment]
This is like a bit complicated because this line operates in more than one transport network.
Therefore I would suggest using the colors communicated by Go-Ahead. I'll add this up to the specs, too.

**Comment by jheubuch** [comment]
I clarified the case "Single line operates in multiple local transport networks"

**Comment by tomabrafix** [comment]
> Therefore I would suggest using the colors communicated by Go-Ahead.

But even Go-Ahead communicates two different colors. Which one of them takes precedence? The color from the network plan or the color from the timetables?


> I'll add this up to the specs, too.

Maybe a priority ranking would be helpful, because sometimes the operator does not communicate a line color and shape at all, e.g. RE16 of DB Regio Bayern AG:

[AVV network plan](https://www.avv-augsburg.de/fileadmin/user_upload/Netzplaene_und_Karten/avv_schienennetzplan_2022_12_web.pdf): #d1050c (+ rounded)
[BEG network plan](https://www.mvv-muenchen.de/fileadmin/mediapool/03-Plaene_Bahnhoefe/Netzplaene/Bahnland-Bayern-Liniennetzplan.pdf): #e50000
DB Regio AG Bayern: _not found_
[VGN network plan](https://www.vgn.de/media/schienennetz-gesamtraum-vgn.pdf): #d91920

For example:
1. operator network plan
2. other resources from operator
3. transport network plan (but which takes more precedence?)
4. local transport authority resources
